cache:
  directories:
    - 'node_modules'
language: node_js
node_js:
  - 'node'
deploy:
  env: $AWSENV
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  skip_cleanup: true
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "$REGION"  
  app: "$APPNAME"
  bucket_name: "$BUCKETNAME"
  on:
    branch: master