cache:
  directories:
    - 'node_modules'
language: node_js
node_js:
  - 'node'
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "$REGION"  
  app: "react-test"
  bucket_name: "$BUCKETNAME"
  on:
    branch: master